/**
 * Created by thejojo on 2017/5/9.
 */
export const NEW_NOTE = 'NEW_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const EDIT_TITLE = 'EDIT_TITLE'
export const EDIT_TODOLIST_TITLE = 'EDIT_TODOLIST_TITLE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const SET_SHOWMODE = 'SET_SHOWMODE'
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE'
export const SET_ACTIVE_TODOLIST = 'SET_ACTIVE_TODOLIST'
export const SET_ACTIVE_TODOLISTCOUNT = 'SET_ACTIVE_TODOLISTCOUNT'

// 注册和登陆相关
export const SET_SHOW_REG = 'SET_SHOW_REG'
export const SET_UNSHOW_REG = 'SET_UNSHOW_REG'
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
// 注册完成后初始化note列表
export const INIT_NOTELIST = 'INIT_NOTELIST'
export const INIT_TODOLIST = 'INIT_TODOLIST'

// 上传leancloud相关
export const SET_ISUPLOADED = 'SET_ISUPLOADED'
export const UPDATE_LOCAL_NOTES = 'UPDATE_LOCAL_NOTES'
export const UPDATE_LOCAL_TODOLISTS = 'UPDATE_LOCAL_TODOLISTS'
export const UPDATE_LOCAL_TODOITEMS = 'UPDATE_LOCAL_TODOITEMS'
export const UPDATE_LOCAL_TODOITEMSADD = 'UPDATE_LOCAL_TODOITEMSADD'
export const UPDATE_TODO_ITEMS_DISPLAY = 'UPDATE_TODO_ITEMS_DISPLAY'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const DELETE_TODOITEM = 'DELETE_TODOITEM'
export const DELETE_TODOITEM_BYID = 'DELETE_TODOITEM_BYID'
export const UPDATE_TODOITEM = 'UPDATE_TODOITEM'
